import Head from 'next/head'
import WithAuthComponent from '../../../src/Hocs/PrivateRoute'
import DashboardLayout from "../../../src/Components/DashLayout"
import AntibioticMain from '../../../src/Components/Pages/Dashboard/Seo/Antibiotic/AntibioticMain'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Foydalanuvchi yaratish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithAuthComponent>
        <DashboardLayout>
          <AntibioticMain/>
        </DashboardLayout>
      </WithAuthComponent>
    </div>
  )
}
