import Head from 'next/head'
import WithAuthComponent from '../../../src/Hocs/PrivateRoute'
import DistrictMain from '../../../src/Components/Pages/Dashboard/Seo/Tuman/DistrictMain'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tuman yaratish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithAuthComponent>
        <DistrictMain />
      </WithAuthComponent>
    </div>
  )
}
